[merchants.sawayaka]
name = "炭焼きレストラン さわやか"
liff_id = "2006055787-m6P6OJ38"
api_base_url = "https://admin.junbanmachi.jp"
origin = "https://exclusive-mini.junbanmachi.jp"
entry_url = "https://exclusive-mini.junbanmachi.jp/sawayaka/"
line_entry_url = "line://app/2006055787-m6P6OJ38"
cover_image_url = "https://admin.junbanmachi.jp/assets/shopimage/66cd1ae04fc15.jpg"
